### ISSUE TITLE
use picsimlab with mplabx 6.15 in ubuntu

### ISSUE THREAD

**Issue by Yasqader** [lcgamboa/picsimlab_md#2]
hi everyone, i'm tring to load a simple hex code generated by mplabx v 6.15 in picsimlab v 0.9.0 231015 linux. the plugin is installed on mplabx but i don't know how it works because i'm new its a little confusing. can anyone help me to resolve this problem?

**Comment by lcgamboa** [comment]
Take a look at the [help tutorial.](https://lcgamboa.github.io/picsimlab_docs/stable/ProgramandDebugPICsimLabWithMPLABX.html)  I have only tested with MPLABX 6.00.

**Comment by Yasqader** [comment]
thank you very much, it works for me.
